### PR TITLE
Support for Elasticsearch 1.6

### PR DESCRIPTION
**Pull request by apeteri**
The changes incorporate @comdiv's modifications from issue #38.

* It seems that `BytesReference`s coming from Netty were also returning `false` for `contentUnsafe`, so propagation of `sourceUnsafe` through request objects and using `source` without a defensive copy can be avoided in all cases (see the javadoc comment on [NettyHttpRequest.java#L117](https://github.com/elastic/elasticsearch/blob/1.5/src/main/java/org/elasticsearch/http/netty/NettyHttpRequest.java#L117)). `contentUnsafe` is missing from ES 1.6, so I have removed all related sections of code.
* ReplicationType is deprecated in ES 1.6, and removed in ES 2.0.
* The test framework adds node settings `"script.indexed": "on"` and `"script.inline": "on"` by default, but complained about `"script.disable_dynamic": false` being added if those two settings are already present. I have removed `script.disable_dynamic` to avoid the test error message.

### CODE REVIEW

**Comment by redserpent7** [comment]
When will this get officially released, I need to update to 1.6 and the only thing preventing me is this plugin

**Comment by sbeam** [comment]
found.elastic.co has stated "starting on August 20th, we will upgrade any cluster on versions older than 1.6.1 to 1.7.0 or newer" due to [security vulns discovered in earlier versions](https://www.elastic.co/blog/elasticsearch-1-7-0-and-1-6-1-released). It would be great to get this version support out there before that happens if at all possible - would this work with 1.7?

**Comment by ofavre** [comment]
v2.6.0, supporting ES 1.6.x is not released and should be available within 2-4 hours.

Thank you very much for this PR!

**Comment by ofavre** [comment]
v2.6.0 supports ES 1.7.1 as well.

**Pull request merged**
